// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculationDataAPI.Context;

namespace TaxCalculationDataAPI.Migrations
{
    [DbContext(typeof(TaxDbContext))]
    partial class TaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaxCalculationDataAPI.Context.Tax", b =>
                {
                    b.Property<int>("TaxId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date");

                    b.Property<string>("MunicipalityName");

                    b.Property<double>("TaxRate");

                    b.HasKey("TaxId");

                    b.ToTable("Taxes");

                    b.HasData(
                        new { TaxId = 2, Date = "2016.07.10", MunicipalityName = "Copenhagen", TaxRate = 0.2 },
                        new { TaxId = 3, Date = "2016.05.02", MunicipalityName = "Copenhagen", TaxRate = 0.4 },
                        new { TaxId = 4, Date = "2016.01.01", MunicipalityName = "Copenhagen", TaxRate = 0.1 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
